// Generated by https://quicktype.io

export interface APIResponse {
  total_count: number;
  results:     Region[] | Province[] | Municipality[];
}

/* export interface Result {
  name: string;
} */

export interface Region {
  acom_name: string;
}
export interface Province {
  prov_name: string;
}
export interface Municipality {
  mun_name: string;
  geo_point_2d: geo_point_2d;
}

interface geo_point_2d {
  lon: number;
  lat: number;
}

export interface MunicipalityProperties {
  acom_name: string;
  prov_name: string;
  mun_name: string;
}
