// Generated by https://quicktype.io

export interface Country {
  name: Name;
  flags: Flags;
  capital?: string[];
  population: number;
  currencies?:  { [key: string]: Currency };
  languages?:   { [key: string]: string };
}

export interface CountryFlag {
  flags: Flags
  cca3: string;
}

export interface DialogData {
  code: string;
}

export interface Name {
  common:      string;
}

export interface Flags {
  svg:  string;
}

export interface Currency {
  name:   string;
  symbol: string;
}
